lab08_dbt:
  target: lab08_dev
  outputs:
    lab08_dev:
      type: clickhouse
      host: "{{ env_var('CLICK_HOST') }}"
      port: {{ env_var('CLICK_PORT') | int }}
      user: "{{ env_var('CLICK_USER') }}"
      password: "{{ env_var('CLICK_PASS') }}"
      schema: "{{ env_var('CLICK_DB') }}"
